#!C:\Users\PKevin\anaconda3\envs\AIVTuberSystem_02\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
